name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Vue 3 Application
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: project-sources
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Stop previous
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ${{ vars.SERVER_TARGET_PATH }}
            docker compose down
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Upload new docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: "docker-compose.yml,nginx/*"
          target: ${{ vars.SERVER_TARGET_PATH }}
      - uses: actions/download-artifact@v3
        with:
          name: project-sources
          path: dist
      - name: Upload sources
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: dist
          overwrite: true
          debug: ${{ vars.ACTIONS_DEBUG }}
          target: ${{ vars.SERVER_TARGET_PATH }}
      - name: Start compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd ${{ vars.SERVER_TARGET_PATH }}
            docker compose up -d

